<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="90472" started-at="2016-10-09T09:53:07Z" finished-at="2016-10-09T09:54:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="90472" started-at="2016-10-09T09:53:07Z" finished-at="2016-10-09T09:54:38Z">
      <class name="com.mv4d.oxalis.TestCase3Epi">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.mv4d.oxalis.TestCase3Epi@c038203]" name="beforeTest" is-config="true" duration-ms="14936" started-at="2016-10-09T12:53:07Z" finished-at="2016-10-09T12:53:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testCase3()[pri:0, instance:com.mv4d.oxalis.TestCase3Epi@c038203]" name="testCase3" duration-ms="70830" started-at="2016-10-09T12:53:22Z" finished-at="2016-10-09T12:54:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Targeted element App is not present on screen expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Targeted element App is not present on screen expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mv4d.oxalis.TestCase3Epi.testCase3(TestCase3Epi.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.mv4d.oxalis.TestCase3Epi@c038203]" name="afterTest" is-config="true" duration-ms="4692" started-at="2016-10-09T12:54:33Z" finished-at="2016-10-09T12:54:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.mv4d.oxalis.TestCase3Epi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
